### ISSUE TITLE
Is there any other way besides disabling the 'Unmount module by default' option in KernelSU?

### ISSUE THREAD

**Issue by sabamdarif** [Unofficial-Life/Lawnchair-Launcher-Module#9]
if i disable unmount module by default option in kernelsu app will detact that kernelsu is installer and the only option is to enable unmount module option for each app manually and it takes lot of time and i might forgot some apps this way which will create problem in future,
please let me know which apps are necessary  to unmout module so it will be easier for me

**Comment by Unofficial-Life** [comment]
I don't use KSU so i don't know all the apps, but turning it off won't cause any problems you can use different root hiding methods if it's detected like zygisk assistant, HMA (hide my applist lsposed)
